name: test-adopt-info
base: core20
adopt-info: version-src
summary: Set snap version 
description: |
  Boilerplate
grade: devel
confinement: strict

parts:
  version-src:
    plugin: nil
    source: ./version-src
    override-pull: |
      PROJECT_VERSION=$(cat $SNAPCRAFT_PROJECT_DIR/version-src/current)
      GIT_REVISION=$(git rev-parse --short HEAD)
      snapcraftctl set-version ${PROJECT_VERSION}-$(date +%Y%m%d%H%M%S)+${GIT_REVISION}
    build-packages: [ git ]
