name: path2
base: core22
version: '0.1'
summary: demo for one script calling another
description: |
  Show how one script app can call another. This example
  should succeed as callee.sh is now on the search path.

grade: stable
confinement: strict

apps:
  caller:
    command: caller.sh
    environment:
      PATH: ${SNAP}:${PATH}
  callee:
    command: callee.sh

parts:
  c1:
    source: caller
    plugin: dump
  c2:
    source: callee
    plugin: dump
