name: ld2
base: core22
version: '0.1'
summary: demo setting LD_LIBRARY_PATH globally
description: |
  Demonstrate tweaking LD_LIBRARY_PATH in the global metadata. 

grade: stable
confinement: strict
environment:
  LD_LIBRARY_PATH: "${SNAP}/mylibs:${SNAP_LIBRARY_PATH}"

apps:
  caller:
    command: caller.sh
  callee:
    command: callee.sh

parts:
  c1:
    source: caller
    plugin: dump
  c2:
    source: callee
    plugin: dump
